[package]
authors = ["chevdor <chevdor@gmail.com>"]
edition = "2018"
name = "gh"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
env_logger = "0.8.3"
log = "0.4.14"
regex = "1.5.4"
webbrowser = "0.5.5"

[[bin]]
name = "gh"
path = "src/main.rs"
